server:
  port: 8084

spring:
  application:
    name: cliente-ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
datasource:
  data:
    mongodb:
      uri: mongodb://techchallenge:techchallenge123@mongo:27017/tech-challenge-cliente?authSource=tech-challenge-cliente

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true