server:
  port: 8101

spring:
  application:
    name: produto-ms
  data:
    couchbase:
      connection-string: couchbases://localhost
      username: admin
      password: admin123
      bucket-name: tech-challenge-produto
      env:
        ssl:
          enabled: true
          truststore: path/to/truststore.jks
          truststore-password: your-truststore-password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

